import {
	MdTextFields as TextIcon,
	MdPhoto as PhotoIcon,
	MdEdit as EditIcon,
	MdTune as TuneIcon,
	MdAdd as PlusIcon,
	MdDelete as DeleteIcon,
	MdDeleteOutline as DeleteOutlineIcon,
	MdFormatAlignLeft as AlignLeftIcon,
	MdFormatAlignCenter as AlignCenterIcon,
	MdFormatAlignRight as AlignRightIcon,
	MdFormatBold as BoldIcon,
	MdFormatItalic as ItalicIcon,
	MdDownload as DownloadIcon,
	MdExpandMore as ChevronDown,
	MdExpandLess as ChevronUp,
	Md360 as Rotate360Icon,
	Md3dRotation as Rotation3dIcon,
	MdCheckCircle as CheckCircleIcon,
	MdCrop as CropIcon,
	MdClose as XIcon,
} from "react-icons/md";

export {
	TextIcon,
	PhotoIcon,
	EditIcon,
	TuneIcon,
	PlusIcon,
	DeleteIcon,
	DeleteOutlineIcon,
	AlignLeftIcon,
	AlignCenterIcon,
	AlignRightIcon,
	BoldIcon,
	ItalicIcon,
	DownloadIcon,
	ChevronDown,
	ChevronUp,
	Rotate360Icon,
	Rotation3dIcon,
	CheckCircleIcon,
	CropIcon,
	XIcon,
};
